### ISSUE TITLE
Upon clicking admin login - "this.bookLabel" is null

### ISSUE THREAD

**Issue by PronayTheVirus** [PronayTheVirus/LMSLibraryManagementSystem#1]
After starting the application, whenever I press the librarian login section after entering password, it gives me error saying-Cannot invoke "javafx.scene.control.Label.setText(String)" because "this.bookLabel" is null
I checked the button's fx code, But nothing was wrong there I think. I couldn't figure out what caused this error.. 

(Hello controller line no 171 and line no 191)

it also shows 'this.memberLabel' is null after deleting 'this.bookLabel'

**Comment by SanjayRam07** [comment]
can I work on this issue ?

**Comment by PronayTheVirus** [comment]
yes, Please! @SanjayRam07

**Comment by PronayTheVirus** [comment]
If you need anything else, let me know!

**Comment by SanjayRam07** [comment]
I'm tried to setup it in my local machine.
Now, it shows: SQL Exception occurred, it doesn't connect to MySQL
what should I do?

**Comment by PronayTheVirus** [comment]
I fixed the error bro. It was because I didn't have the controller class for that scene. Please look at my profile for the updated project. 
And about schema info.. what things do you need? I have no idea since I am new to this

**Comment by PronayTheVirus** [comment]
@SanjayRam07

**Comment by PronayTheVirus** [comment]
I hope this helps;

**Comment by SanjayRam07** [comment]
Okk, it's great and thank you. You can close the issue. @PronayTheVirus

**Comment by PronayTheVirus** [comment]
Would you like to share the changes you've made? @SanjayRam07

**Comment by SanjayRam07** [comment]
I had created a pull request in which get the files changed tab and see the
changes.
